export const ACHIEVEMENT_CATEGORIES = {
  bloom:     { label: 'Dr. Bloom',        color: '#1D9E75' },
  care:      { label: 'Care & Vaccines',  color: '#3B82F6' },
  growth:    { label: 'Growth',           color: '#10B981' },
  milestone: { label: 'Milestones',       color: '#8B5CF6' },
};

export const ACHIEVEMENTS = [
  // ── Milestones ────────────────────────────────────────────────
  {
    key: 'welcome',
    title: 'Welcome to Bloom',
    desc: 'Joined the ChildBloom family',
    emoji: '🌱',
    category: 'milestone',
    color: '#1D9E75',
    hint: 'Automatically awarded when you sign up',
  },

  // ── Dr. Bloom ─────────────────────────────────────────────────
  {
    key: 'first_question',
    title: 'First Consult',
    desc: 'Asked Dr. Bloom your very first question',
    emoji: '💬',
    category: 'bloom',
    color: '#1D9E75',
    hint: 'Send any message to Dr. Bloom',
  },
  {
    key: 'bloom_curious',
    title: 'Curious Parent',
    desc: 'Asked Dr. Bloom 5 questions',
    emoji: '🔍',
    category: 'bloom',
    color: '#1D9E75',
    threshold: 5,
    hint: '5 questions asked',
  },
  {
    key: 'bloom_regular',
    title: 'Regular Patient',
    desc: 'Asked Dr. Bloom 10 questions',
    emoji: '📋',
    category: 'bloom',
    color: '#059669',
    threshold: 10,
    hint: '10 questions asked',
  },
  {
    key: 'bloom_devoted',
    title: 'Devoted Parent',
    desc: 'Trusted Dr. Bloom with 25 questions',
    emoji: '❤️',
    category: 'bloom',
    color: '#E11D48',
    threshold: 25,
    hint: '25 questions asked',
  },
  {
    key: 'bloom_expert',
    title: 'Bloom Expert',
    desc: 'Asked Dr. Bloom 50 questions — you\'re a pro',
    emoji: '🏆',
    category: 'bloom',
    color: '#D97706',
    threshold: 50,
    hint: '50 questions asked',
  },
  {
    key: 'night_owl',
    title: 'Night Owl',
    desc: 'Asked Dr. Bloom after 10pm — we\'re here for you',
    emoji: '🌙',
    category: 'bloom',
    color: '#6366F1',
    hint: 'Ask a question after 10pm',
  },
  {
    key: 'early_bird',
    title: 'Early Bird',
    desc: 'Asked Dr. Bloom before 6am — dedication!',
    emoji: '🌅',
    category: 'bloom',
    color: '#F59E0B',
    hint: 'Ask a question before 6am',
  },

  // ── Care & Vaccines ───────────────────────────────────────────
  {
    key: 'first_vaccine',
    title: 'First Shield',
    desc: 'Logged your first vaccination',
    emoji: '💉',
    category: 'care',
    color: '#3B82F6',
    hint: 'Mark any vaccine as given',
  },
  {
    key: 'vaccine_5',
    title: 'Immunity Builder',
    desc: 'Logged 5 vaccinations',
    emoji: '🛡️',
    category: 'care',
    color: '#2563EB',
    hint: '5 vaccines logged',
  },
  {
    key: 'vaccine_half',
    title: 'Halfway Hero',
    desc: 'Completed 50% of the IAP vaccine schedule',
    emoji: '⭐',
    category: 'care',
    color: '#D97706',
    hint: 'Complete 50% of the vaccine schedule',
  },

  // ── Growth ────────────────────────────────────────────────────
  {
    key: 'first_measurement',
    title: 'First Measurement',
    desc: 'Logged your first growth measurement',
    emoji: '📏',
    category: 'growth',
    color: '#10B981',
    hint: 'Add a growth measurement',
  },
  {
    key: 'growth_5',
    title: 'Growth Champion',
    desc: 'Logged 5 growth measurements — tracking like a pro',
    emoji: '📈',
    category: 'growth',
    color: '#059669',
    hint: '5 measurements logged',
  },
];
