export const ACHIEVEMENT_CATEGORIES = {
  bloom:     { label: 'Dr. Bloom',        color: '#1D9E75' },
  care:      { label: 'Care & Vaccines',  color: '#3B82F6' },
  growth:    { label: 'Growth',           color: '#10B981' },
  milestone: { label: 'Milestones',       color: '#8B5CF6' },
  rhythm:    { label: 'Daily Rhythm',     color: '#0EA5E9' },
};

export const ACHIEVEMENTS = [
  // ── Milestones ────────────────────────────────────────────────
  {
    key: 'welcome',
    title: 'Welcome to Bloom',
    desc: 'Joined the ChildBloom family',
    emoji: '🌱',
    category: 'milestone',
    color: '#1D9E75',
    hint: 'Automatically awarded when you sign up',
  },

  // ── Dr. Bloom ─────────────────────────────────────────────────
  {
    key: 'first_question',
    title: 'First Consult',
    desc: 'Asked Dr. Bloom your very first question',
    emoji: '💬',
    category: 'bloom',
    color: '#1D9E75',
    hint: 'Send any message to Dr. Bloom',
  },
  {
    key: 'bloom_curious',
    title: 'Curious Parent',
    desc: 'Asked Dr. Bloom 5 questions',
    emoji: '🔍',
    category: 'bloom',
    color: '#1D9E75',
    threshold: 5,
    hint: '5 questions asked',
  },
  {
    key: 'bloom_regular',
    title: 'Regular Patient',
    desc: 'Asked Dr. Bloom 10 questions',
    emoji: '📋',
    category: 'bloom',
    color: '#059669',
    threshold: 10,
    hint: '10 questions asked',
  },
  {
    key: 'bloom_devoted',
    title: 'Devoted Parent',
    desc: 'Trusted Dr. Bloom with 25 questions',
    emoji: '❤️',
    category: 'bloom',
    color: '#E11D48',
    threshold: 25,
    hint: '25 questions asked',
  },
  {
    key: 'bloom_expert',
    title: 'Bloom Expert',
    desc: 'Asked Dr. Bloom 50 questions — you\'re a pro',
    emoji: '🏆',
    category: 'bloom',
    color: '#D97706',
    threshold: 50,
    hint: '50 questions asked',
  },
  {
    key: 'night_owl',
    title: 'Night Owl',
    desc: 'Asked Dr. Bloom after 10pm — we\'re here for you',
    emoji: '🌙',
    category: 'bloom',
    color: '#6366F1',
    hint: 'Ask a question after 10pm',
  },
  {
    key: 'early_bird',
    title: 'Early Bird',
    desc: 'Asked Dr. Bloom before 6am — dedication!',
    emoji: '🌅',
    category: 'bloom',
    color: '#F59E0B',
    hint: 'Ask a question before 6am',
  },

  // ── Care & Vaccines ───────────────────────────────────────────
  {
    key: 'first_vaccine',
    title: 'First Shield',
    desc: 'Logged your first vaccination',
    emoji: '💉',
    category: 'care',
    color: '#3B82F6',
    hint: 'Mark any vaccine as given',
  },
  {
    key: 'vaccine_5',
    title: 'Immunity Builder',
    desc: 'Logged 5 vaccinations',
    emoji: '🛡️',
    category: 'care',
    color: '#2563EB',
    hint: '5 vaccines logged',
  },
  {
    key: 'vaccine_half',
    title: 'Halfway Hero',
    desc: 'Completed 50% of the IAP vaccine schedule',
    emoji: '⭐',
    category: 'care',
    color: '#D97706',
    hint: 'Complete 50% of the vaccine schedule',
  },

  // ── Daily Rhythm (logging) ───────────────────────────────────
  {
    key: 'first_log',
    title: 'First Drop',
    desc: 'Logged your very first feed, sleep or diaper',
    emoji: '💧',
    category: 'rhythm',
    color: '#0EA5E9',
    hint: 'Log anything — a feed, a nap, a diaper',
  },
  {
    key: 'first_voice_log',
    title: 'Just Said It',
    desc: 'Logged hands-free with your voice',
    emoji: '🎙️',
    category: 'rhythm',
    color: '#0EA5E9',
    hint: 'Use the mic to log something',
  },
  {
    key: 'night_hero',
    title: '3am Hero',
    desc: 'Logged in the small hours — we see you',
    emoji: '🌃',
    category: 'rhythm',
    color: '#6366F1',
    hint: 'Save a log between midnight and 5am',
  },
  {
    key: 'full_picture',
    title: 'Full Picture',
    desc: 'Feed, sleep and diaper — all in one day',
    emoji: '🧩',
    category: 'rhythm',
    color: '#0284C7',
    hint: 'Log all three types in a single day',
  },
  {
    key: 'streak_3',
    title: 'Three in a Row',
    desc: '3 days of logging — a rhythm is forming',
    emoji: '🌿',
    category: 'rhythm',
    color: '#0EA5E9',
    threshold: 3,
    hint: 'Log on 3 days in a row',
  },
  {
    key: 'streak_7',
    title: 'One Full Week',
    desc: '7 straight days — the garden never went dry',
    emoji: '🌼',
    category: 'rhythm',
    color: '#0284C7',
    threshold: 7,
    hint: 'Log on 7 days in a row',
  },
  {
    key: 'streak_14',
    title: 'Fortnight of Care',
    desc: '14 consecutive days of showing up',
    emoji: '🌸',
    category: 'rhythm',
    color: '#7C3AED',
    threshold: 14,
    hint: 'Log on 14 days in a row',
  },
  {
    key: 'streak_30',
    title: 'A Whole Month',
    desc: '30 days straight — this is devotion',
    emoji: '🏵️',
    category: 'rhythm',
    color: '#D97706',
    threshold: 30,
    hint: 'Log on 30 days in a row',
  },
  {
    key: 'logs_100',
    title: 'Century of Care',
    desc: '100 logs — every one a small act of love',
    emoji: '💯',
    category: 'rhythm',
    color: '#E11D48',
    threshold: 100,
    hint: 'Save 100 logs in total',
  },

  // ── Growth ────────────────────────────────────────────────────
  {
    key: 'first_measurement',
    title: 'First Measurement',
    desc: 'Logged your first growth measurement',
    emoji: '📏',
    category: 'growth',
    color: '#10B981',
    hint: 'Add a growth measurement',
  },
  {
    key: 'growth_5',
    title: 'Growth Champion',
    desc: 'Logged 5 growth measurements — tracking like a pro',
    emoji: '📈',
    category: 'growth',
    color: '#059669',
    hint: '5 measurements logged',
  },
];
