-- 018_daily_brief.sql
-- Daily "Bloom Brief" — one short, personalised card per child per day.
-- The retention hook: a reason to open ChildBloom every morning without logging.
--
-- Rows are generated by the cron (api/agent/cron.js) using the Child Profile
-- Folder + Claude, and written ONLY by the service role. Parents READ their own.
-- Idempotent + self-contained — safe to paste into the Supabase SQL editor.

create table if not exists public.daily_brief (
  id               uuid primary key default gen_random_uuid(),
  child_id         uuid not null references public.children (id) on delete cascade,
  user_id          uuid not null references auth.users (id)      on delete cascade,
  brief_date       date not null,
  title            text not null,
  expect_this_week text,
  tip              text,
  reassurance      text,
  lang             text not null default 'en',
  created_at       timestamptz not null default now(),
  unique (child_id, brief_date)
);

create index if not exists daily_brief_child_date_idx
  on public.daily_brief (child_id, brief_date desc);

alter table public.daily_brief enable row level security;

-- Owners may READ their own briefs. No insert/update/delete policy exists,
-- so only the service role (cron) can write.
drop policy if exists "own brief read" on public.daily_brief;
create policy "own brief read"
  on public.daily_brief
  for select
  using (auth.uid() = user_id);
